AllCops:
  DisplayCopNames: true
  Exclude:
    - db/migrate/*.rb

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Exclude:
    - Gemfile

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Lint/HandleExceptions:
  Exclude:
    - bin/rails
    - bin/rake

Style/RaiseArgs:
  EnforcedStyle: compact
